import { Routes } from '@angular/router';

import { Home } from './pages/home/home';
import { Community } from './pages/community/community';
import { Login } from './pages/login/login';
import { Agreement } from './pages/agreement/agreement';
import { Goodbye } from './pages/goodbye/goodbye';
import { AccountDeletion } from './pages/account-deletion/account-deletion';
import { Farewell } from './pages/farewell/farewell';
import { Register } from './pages/register/register';
import { PostTypesSelection } from './pages/post-types-selection/post-types-selection';
import { PostsList } from './pages/posts-list/posts-list';
import { Post } from './pages/post/post';
import { PostCreate } from './pages/post-create/post-create';
import { Favorites } from './pages/favorites/favorites';
import { Network } from './pages/network/network';
import { MyArea } from './pages/my-area/my-area';
import { UserProfile } from './pages/user-profile/user-profile';
import { BadGateway } from './pages/bad-gateway/bad-gateway';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'my-area', component: MyArea },
  { path: 'favorites', component: Favorites },
  { path: 'network', component: Network },
  { path: 'community', component: Community },
  { path: 'login', component: Login },
  { path: 'agreement', component: Agreement },
  { path: 'goodbye', component: Goodbye },
  { path: 'account-deletion', component: AccountDeletion },
  { path: 'farewell', component: Farewell },
  { path: 'register', component: Register },
  { path: 'post-types-selection', component: PostTypesSelection },
  { path: 'posts-list', component: PostsList },
  { path: 'post/:id', component: Post },
  { path: 'post-create', component: PostCreate },
  { path: 'user-profile/:id', component: UserProfile },
  { path: 'bad-gateway', component: BadGateway },
];
