const JAVASCRIPT_LANGUAGES: { [key: string]: string } = {
  // Core Runtimes & Languages
  'node.js': 'javascript',

  // Frontend Frameworks
  react: 'jsx',
  'vue.js': 'javascript',
  svelte: 'javascript',
  angular: 'typescript',
  solidjs: 'javascript',
  qwik: 'jsx',

  // Backend & API
  express: 'javascript',
  nestjs: 'typescript',
  fastify: 'javascript',
  trpc: 'typescript',

  // Full-Stack Frameworks
  'next.js': 'jsx',
  nuxt: 'javascript',
  remix: 'jsx',
  gatsby: 'jsx',
  astro: 'jsx',

  // Libraries
  jquery: 'javascript',
  rxjs: 'typescript',
  axios: 'javascript',
  lodash: 'javascript',
  'socket.io': 'javascript',
  'chart.js': 'javascript',
  'd3.js': 'javascript',
  'three.js': 'javascript',
  swiper: 'javascript',

  // ORM/DB
  prisma: 'typescript',
  sequelize: 'javascript',
  mongoose: 'javascript',

  // Authentication
  passport: 'javascript',

  // Cross-Platform Frameworks
  'react native': 'jsx',
  electron: 'javascript',
  'inertia.js': 'javascript',
};

const PYTHON_LANGUAGES: { [key: string]: string } = {
  // Data Science & ML
  numpy: 'python',
  pandas: 'python',
  tensorflow: 'python',
  keras: 'python',
  pytorch: 'python',
  plotly: 'python',

  // ORM & Tools
  sqlalchemy: 'python',
};

const JAVA_LANGUAGES: { [key: string]: string } = {
  // Frameworks
  spring: 'java',
  springboot: 'java',

  // Libraries & Tools
  hibernate: 'java',
};

const PHP_LANGUAGES: { [key: string]: string } = {
  // Frameworks
  laravel: 'php',
  symfony: 'php',
  lumen: 'php',
  codeigniter: 'php',

  // ORM
  doctrine: 'php',
};

const CSHARP_LANGUAGES: { [key: string]: string } = {
  blazor: 'csharp',
  'ef core': 'csharp',
};

const CSS_LANGUAGES: { [key: string]: string } = {
  bootstrap: 'css',
  bulma: 'css',
  foundation: 'css',
  materialize: 'css',
  tailwind: 'css',
};

const OTHER_LANGUAGES: { [key: string]: string } = {
  // Cross-Platform Frameworks
  'ruby on rails': 'ruby',
  phoenix: 'elixir',
  fiber: 'go',
  flutter: 'dart',
  tauri: 'rust',

  // Game Engines & Frameworks
  'bevy engine': 'rust',
  'bash/shell': 'bash',
};

export const CUSTOM_PRISM_LANGUAGES: { [key: string]: string } = {
  ...JAVASCRIPT_LANGUAGES,
  ...PYTHON_LANGUAGES,
  ...JAVA_LANGUAGES,
  ...PHP_LANGUAGES,
  ...CSHARP_LANGUAGES,
  ...CSS_LANGUAGES,
  ...OTHER_LANGUAGES,
};

export const DEFAULT_PRISM_LANGUAGES: { [key: string]: string } = {
  markup: 'markup',
  html: 'markup',
  xml: 'markup',
  svg: 'markup',
  mathml: 'markup',
  ssml: 'markup',
  atom: 'markup',
  rss: 'markup',
  css: 'css',
  clike: 'clike',
  javascript: 'javascript',
  js: 'javascript',
  abap: 'abap',
  abnf: 'abnf',
  actionscript: 'actionscript',
  ada: 'ada',
  agda: 'agda',
  al: 'al',
  antlr4: 'antlr4',
  g4: 'antlr4',
  apacheconf: 'apacheconf',
  apex: 'apex',
  apl: 'apl',
  applescript: 'applescript',
  aql: 'aql',
  arduino: 'arduino',
  ino: 'arduino',
  arff: 'arff',
  armasm: 'armasm',
  'arm-asm': 'armasm',
  arturo: 'arturo',
  art: 'arturo',
  asciidoc: 'asciidoc',
  adoc: 'asciidoc',
  aspnet: 'aspnet',
  asm6502: 'asm6502',
  asmatmel: 'asmatmel',
  autohotkey: 'autohotkey',
  autoit: 'autoit',
  avisynth: 'avisynth',
  avs: 'avisynth',
  'avro-idl': 'avro-idl',
  avdl: 'avro-idl',
  awk: 'awk',
  gawk: 'awk',
  bash: 'bash',
  sh: 'bash',
  shell: 'bash',
  basic: 'basic',
  batch: 'batch',
  bbcode: 'bbcode',
  shortcode: 'bbcode',
  bbj: 'bbj',
  bicep: 'bicep',
  birb: 'birb',
  bison: 'bison',
  bnf: 'bnf',
  rbnf: 'bnf',
  bqn: 'bqn',
  brainfuck: 'brainfuck',
  brightscript: 'brightscript',
  bro: 'bro',
  bsl: 'bsl',
  oscript: 'bsl',
  c: 'c',
  'c#': 'csharp',
  csharp: 'csharp',
  cs: 'csharp',
  dotnet: 'csharp',
  'c++': 'cpp',
  cpp: 'cpp',
  cfscript: 'cfscript',
  cfc: 'cfscript',
  chaiscript: 'chaiscript',
  cil: 'cil',
  cilkc: 'cilkc',
  'cilk-c': 'cilkc',
  cilkcpp: 'cilkcpp',
  'cilk-cpp': 'cilkcpp',
  cilk: 'cilkcpp',
  clojure: 'clojure',
  cmake: 'cmake',
  cobol: 'cobol',
  coffeescript: 'coffeescript',
  coffee: 'coffeescript',
  concurnas: 'concurnas',
  conc: 'concurnas',
  csp: 'csp',
  cooklang: 'cooklang',
  coq: 'coq',
  crystal: 'crystal',
  'css-extras': 'css-extras',
  csv: 'csv',
  cue: 'cue',
  cypher: 'cypher',
  d: 'd',
  dart: 'dart',
  dataweave: 'dataweave',
  dax: 'dax',
  dhall: 'dhall',
  diff: 'diff',
  django: 'django',
  jinja2: 'django',
  'dns-zone-file': 'dns-zone-file',
  'dns-zone': 'dns-zone-file',
  docker: 'docker',
  dockerfile: 'docker',
  dot: 'dot',
  gv: 'dot',
  ebnf: 'ebnf',
  editorconfig: 'editorconfig',
  eiffel: 'eiffel',
  ejs: 'ejs',
  eta: 'ejs',
  elixir: 'elixir',
  elm: 'elm',
  etlua: 'etlua',
  erb: 'erb',
  erlang: 'erlang',
  'excel-formula': 'excel-formula',
  xlsx: 'excel-formula',
  xls: 'excel-formula',
  fsharp: 'fsharp',
  'f#': 'fsharp',
  factor: 'factor',
  false: 'false',
  'firestore-security-rules': 'firestore-security-rules',
  flow: 'flow',
  fortran: 'fortran',
  ftl: 'ftl',
  gml: 'gml',
  gamemakerlanguage: 'gml',
  gap: 'gap',
  'g-code': 'gcode',
  gdscript: 'gdscript',
  gedcom: 'gedcom',
  gettext: 'gettext',
  po: 'gettext',
  gherkin: 'gherkin',
  git: 'git',
  glsl: 'glsl',
  gn: 'gn',
  gni: 'gn',
  'linker-script': 'linker-script',
  ld: 'linker-script',
  go: 'go',
  'go-module': 'go-module',
  'go-mod': 'go-module',
  gradle: 'gradle',
  graphql: 'graphql',
  groovy: 'groovy',
  haml: 'haml',
  handlebars: 'handlebars',
  hbs: 'handlebars',
  mustache: 'handlebars',
  haskell: 'haskell',
  hs: 'haskell',
  haxe: 'haxe',
  hcl: 'hcl',
  hlsl: 'hlsl',
  hoon: 'hoon',
  http: 'http',
  hpkp: 'hpkp',
  hsts: 'hsts',
  ichigojam: 'ichigojam',
  icon: 'icon',
  'icu-message-format': 'icu-message-format',
  idris: 'idris',
  idr: 'idris',
  ignore: 'ignore',
  gitignore: 'ignore',
  hgignore: 'ignore',
  npmignore: 'ignore',
  inform7: 'inform7',
  ini: 'ini',
  io: 'io',
  j: 'j',
  java: 'java',
  javadoc: 'javadoc',
  javadoclike: 'javadoclike',
  javastacktrace: 'javastacktrace',
  jexl: 'jexl',
  jolie: 'jolie',
  jq: 'jq',
  jsdoc: 'jsdoc',
  'js-extras': 'js-extras',
  json: 'json',
  webmanifest: 'json',
  json5: 'json5',
  jsonp: 'jsonp',
  jsstacktrace: 'jsstacktrace',
  'js-templates': 'js-templates',
  julia: 'julia',
  keepalived: 'keepalived',
  keyman: 'keyman',
  kotlin: 'kotlin',
  kt: 'kotlin',
  kts: 'kotlin',
  kumir: 'kumir',
  kum: 'kumir',
  kusto: 'kusto',
  latex: 'latex',
  tex: 'latex',
  context: 'latex',
  latte: 'latte',
  less: 'less',
  lilypond: 'lilypond',
  ly: 'lilypond',
  liquid: 'liquid',
  lisp: 'lisp',
  emacs: 'lisp',
  elisp: 'lisp',
  'emacs-lisp': 'lisp',
  livescript: 'livescript',
  llvm: 'llvm',
  log: 'log',
  lolcode: 'lolcode',
  lua: 'lua',
  magma: 'magma',
  makefile: 'makefile',
  markdown: 'markdown',
  md: 'markdown',
  'markup-templating': 'markup-templating',
  mata: 'mata',
  matlab: 'matlab',
  maxscript: 'maxscript',
  mel: 'mel',
  mermaid: 'mermaid',
  metafont: 'metafont',
  mizar: 'mizar',
  mongodb: 'mongodb',
  monkey: 'monkey',
  moonscript: 'moonscript',
  moon: 'moonscript',
  n1ql: 'n1ql',
  n4js: 'n4js',
  n4jsd: 'n4js',
  'nand2tetris-hdl': 'nand2tetris-hdl',
  naniscript: 'naniscript',
  nani: 'naniscript',
  nasm: 'nasm',
  neon: 'neon',
  nevod: 'nevod',
  nginx: 'nginx',
  nim: 'nim',
  nix: 'nix',
  nsis: 'nsis',
  objectivec: 'objectivec',
  objc: 'objectivec',
  ocaml: 'ocaml',
  odin: 'odin',
  opencl: 'opencl',
  openqasm: 'openqasm',
  qasm: 'openqasm',
  oz: 'oz',
  parigp: 'parigp',
  parser: 'parser',
  pascal: 'pascal',
  objectpascal: 'pascal',
  pascaligo: 'pascaligo',
  psl: 'psl',
  pcaxis: 'pcaxis',
  px: 'pcaxis',
  peoplecode: 'peoplecode',
  pcode: 'peoplecode',
  perl: 'perl',
  php: 'php',
  phpdoc: 'phpdoc',
  'php-extras': 'php-extras',
  'plant-uml': 'plant-uml',
  plantuml: 'plant-uml',
  plsql: 'plsql',
  powerquery: 'powerquery',
  pq: 'powerquery',
  mscript: 'powerquery',
  powershell: 'powershell',
  processing: 'processing',
  prolog: 'prolog',
  promql: 'promql',
  properties: 'properties',
  protobuf: 'protobuf',
  pug: 'pug',
  puppet: 'puppet',
  pure: 'pure',
  purebasic: 'purebasic',
  pbfasm: 'purebasic',
  purescript: 'purescript',
  purs: 'purescript',
  python: 'python',
  py: 'python',
  qsharp: 'qsharp',
  qs: 'qsharp',
  q: 'q',
  qml: 'qml',
  qore: 'qore',
  r: 'r',
  racket: 'racket',
  rkt: 'racket',
  cshtml: 'cshtml',
  razor: 'cshtml',
  jsx: 'jsx',
  tsx: 'tsx',
  reason: 'reason',
  regex: 'regex',
  rego: 'rego',
  renpy: 'renpy',
  rpy: 'renpy',
  rescript: 'rescript',
  res: 'rescript',
  rest: 'rest',
  rip: 'rip',
  roboconf: 'roboconf',
  robotframework: 'robotframework',
  robot: 'robotframework',
  ruby: 'ruby',
  rb: 'ruby',
  rust: 'rust',
  sas: 'sas',
  sass: 'sass',
  scss: 'scss',
  scala: 'scala',
  scheme: 'scheme',
  'shell-session': 'shell-session',
  'sh-session': 'shell-session',
  shellsession: 'shell-session',
  smali: 'smali',
  smalltalk: 'smalltalk',
  smarty: 'smarty',
  sml: 'sml',
  smlnj: 'sml',
  solidity: 'solidity',
  sol: 'solidity',
  'solution-file': 'solution-file',
  sln: 'solution-file',
  soy: 'soy',
  sparql: 'sparql',
  rq: 'sparql',
  'splunk-spl': 'splunk-spl',
  sqf: 'sqf',
  sql: 'sql',
  squirrel: 'squirrel',
  stan: 'stan',
  stata: 'stata',
  iecst: 'iecst',
  stylus: 'stylus',
  supercollider: 'supercollider',
  sclang: 'supercollider',
  swift: 'swift',
  systemd: 'systemd',
  't4-templating': 't4-templating',
  't4-cs': 't4-cs',
  t4: 't4-cs',
  't4-vb': 't4-vb',
  tap: 'tap',
  tcl: 'tcl',
  tt2: 'tt2',
  textile: 'textile',
  toml: 'toml',
  tremor: 'tremor',
  trickle: 'tremor',
  troy: 'tremor',
  turtle: 'turtle',
  trig: 'turtle',
  twig: 'twig',
  typescript: 'typescript',
  ts: 'typescript',
  typoscript: 'typoscript',
  tsconfig: 'typoscript',
  unrealscript: 'unrealscript',
  uscript: 'unrealscript',
  uc: 'unrealscript',
  uorazor: 'uorazor',
  uri: 'uri',
  url: 'uri',
  v: 'v',
  vala: 'vala',
  vbnet: 'vbnet',
  velocity: 'velocity',
  verilog: 'verilog',
  vhdl: 'vhdl',
  vim: 'vim',
  'visual-basic': 'visual-basic',
  vb: 'visual-basic',
  vba: 'visual-basic',
  warpscript: 'warpscript',
  wasm: 'wasm',
  'web-idl': 'web-idl',
  webidl: 'web-idl',
  wgsl: 'wgsl',
  wiki: 'wiki',
  wolfram: 'wolfram',
  mathematica: 'wolfram',
  nb: 'wolfram',
  wl: 'wolfram',
  wren: 'wren',
  xeora: 'xeora',
  xeoracube: 'xeora',
  'xml-doc': 'xml-doc',
  xojo: 'xojo',
  xquery: 'xquery',
  yaml: 'yaml',
  yml: 'yaml',
  yang: 'yang',
  zig: 'zig',
};
